### ISSUE TITLE
保存openai_api

### ISSUE THREAD

**Issue by gyxxgzy** [LiuZhenyan-Wuzhong/ChatGlider#1]
现在好像关机后再重启应用会导致之前输入的api消失，得重新输入一次，感觉有点不方便（

版本：v1.0.2
系统：Windows 11 22624.1755

**Comment by LiuZhenyan-Wuzhong** [comment]
![image](https://github.com/LiuZhenyan-Wuzhong/ChatGlider/assets/56421773/72fc878f-7fc6-4780-bd9c-e7187db7f347)
每次进行保存时都会尝试将用户数据写入到用户本地的存储目录，如果保存时没有弹出如下的显示框说明存在保存失败的情况。
![image](https://github.com/LiuZhenyan-Wuzhong/ChatGlider/assets/56421773/bbeda535-27e6-4192-9061-1a57e34eb4ca)
请使用管理员权限运行，管理员权限也会影响软件对于鼠标事件的监听。

**Comment by gyxxgzy** [comment]
每次打开的时候是用管理员权限运行的，这个弹窗确实也出现了（
我再观察下，如果不是大范围问题的话可能是我自己配置的问题，但是您提到的这两点确实是都满足的

**Comment by LiuZhenyan-Wuzhong** [comment]
我这儿没复现了，但是刚刚找人试了下，也是这个问题，我会修复一下。
有别的意见也请多多提出。

**Comment by gyxxgzy** [comment]
好的好的，麻烦了

**Comment by LiuZhenyan-Wuzhong** [comment]
解决了,是我自己傻了, 搞成仅开发模式才会保存配置了, 你可以从release中down下来试下. 有其他的建议和bug都欢迎提出.

**Comment by gyxxgzy** [comment]
v1.0.3 实测正常了，感谢感谢

**Comment by LiuZhenyan-Wuzhong** [comment]
ok，不用谢，那我关闭这个issue了。
